# version: '3.8'

volumes:
  pgdata_atrucks_swk:

networks:
    atrucks_network_swk:
        driver: bridge

services:

  db:
    image: postgres:16
    container_name: atrucks_pg_swk
    restart: "no"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # - ./db/50-init.sql:/docker-entrypoint-initdb.d/50-init.sql
      # - ./db/60-init.sql:/docker-entrypoint-initdb.d/60-init.sql
      - ./db/60-init.sql:/docker-entrypoint-initdb.d/60-init.sql
      # - ./db/init.sh:/docker-entrypoint-initdb.d/70-init.sh
      - pgdata_atrucks_swk:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_EXPOSE}:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - atrucks_network_swk

  back:
    container_name: atrucks_back_swk
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=db
      - REDIS_PORT=${REDIS_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    restart: "no"
    build:
      context: ..
      dockerfile: docker/back/Dockerfile
    volumes:
      - ../logs:/app/logs
      - ../static:/app/static
      - ../files:/app/files
      - ../backend/src:/app/backend/src
    working_dir: /app/backend/src
    command: bash -c "uv run manage.py migrate && \
      uv run manage.py collectstatic --noinput && \
      uv run manage.py create_admin && \
      uv run manage.py force_update && \
      uv run gunicorn core.wsgi:application --pid ../../run/backend.pid \
        -b 0.0.0.0:${BACK_SERVER_PORT} --preload --threads 4 --workers 1"
    ports:
      - ${BACK_SERVER_PORT}:${BACK_SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      celery:
        condition: service_started
    links:
      - redis
    networks:
      - atrucks_network_swk
    # extra_hosts:
    #   - "host.docker.internal:host-gateway" # local

  redis:
    container_name: atrucks_redis_swk
    image: "redis:latest"
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "protected-mode no" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${REDIS_PORT_EXPOSE}:${REDIS_PORT}
    networks:
      - atrucks_network_swk

  celery:
    image: "docker-back"
    container_name: atrucks_celery_swk
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=db
      - REDIS_PORT=${REDIS_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    restart: "no"
    volumes:
      - ../logs:/app/logs
      - ../static:/app/static
      - ../files:/app/files
      - ../backend/src:/app/backend/src
    working_dir: /app/backend/src
    # command: bash -c "sleep infinity"
    # command: bash -c "apt update && apt install redis-tools && apt install iputils-ping && apt install nmap & sleep infinity"
    command: bash -c "uv run celery -A core worker -B --loglevel=INFO"
    depends_on:
      # back:
      #   condition: service_started
      redis:
        condition: service_started
    links:
      - redis
    networks:
      - atrucks_network_swk
    extra_hosts:
      - "host.docker.internal:host-gateway" # local


  nginx:
    container_name: atrucks_nginx_swk
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: "no"
    depends_on:
      - back
    ports:
      - 8001:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./static:/app/static
    networks:
      - atrucks_network_swk

# sudo docker compose up --build --abort-on-container-exit --remove-orphans